<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
  <title>404 File Not Found</title>
  <link rel="stylesheet" href="http://www.twinaxis.com/ta_styles.css" type="text/css" />
</head>

<body>
  <div id="twinaxisheader">

    <div id="title">
      404 File Not Found
    </div>

    <div id="navigation">
      [ <a href="http://www.twinaxis.com/index.html">Home</a> ]
      [ <a href="http://www.twinaxis.com/about.html">About</a> ]
      [ <a href="http://www.twinaxis.com/members.html">Members</a> ]
      [ <a href="http://www.twinaxis.com/projects.html">Projects</a> ]
    </div>

    <div class="hidden"><hr /></div>

  </div>


  <div id="twinaxiscontentarea">

    <p class="header">
      File Not Found
    </p>
    <p class="text">
      Sorry, the requested URL was not found.
    </p>
    <p class="text">
      You tried to access the URL [
      <span class="monobold"><?php
          echo "http://" . $HTTP_HOST . $REQUEST_URI;
      ?></span>
      ] from the URL [
      <span class="monobold"><?php
          if ($REDIRECT_URL == "404.phtml")
          {
            echo "http://" . $HTTP_HOST . $REDIRECT_URL;
          }
          else
          {
            echo "unknown";
          }
      ?></span>
      ].
    </p>
    <p class="text">
      If you feel like it, mail the URL and where you linked from to the
      <a href="mailto:webmaster@twinaxis.com">WebMaster</a>.
    </p>

  </div>


  <div id="twinaxisfooter">

    <div class="hidden"><hr /></div>

    <p class="text">
      <a href="http://validator.w3.org/check/referer"><img
        src="http://www.twinaxis.com/images/valid-xhtml10.png" alt="Valid XHTML 1.0!"
        height="31" width="88" style="border: 0px; float: right" /></a>

      <a href="http://jigsaw.w3.org/css-validator/check/referer"><img
        src="http://www.twinaxis.com/images/valid-css2.png" 
        alt="Valid CSS!" height="31" width="88"
        style="border: 0px; float: right" /></a>

      Please direct all inquiries to <a href="mailto:webmaster@twinaxis.com">webmaster@twinaxis.com</a>.
    </p>

    <p class="text">
    </p>

  </div>

</body>

</html>
